services:
  api:
    build: .
    container_name: devops_api
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: devops_db
    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata_dev:
