version: '3.8'

services:
  api:
    image: herve19944/devops-ci-cd-project-api:latest
    container_name: devops_api_prod
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    restart: always

  client:  
    image: herve19944/qcm-frontend:latest
    container_name: qcm_front
    ports:
      - "8080:80"  # On ouvre sur 8080 pour laisser le 80 libre pour Nginx
    restart: always