apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qcm-ingress
  namespace: qcm-app
  annotations:
    # On utilise Nginx comme contrôleur d'entrée
    kubernetes.io/ingress.class: nginx
    # Pour le certificat SSL automatique (on le configurera plus tard)
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    # Règle pour l'API
    - host: api.next-itsolutions.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
    # Règle pour le Frontend
    - host: www.front.next-itsolutions.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80