name: ðŸš€ Build & Deploy to VPS

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'
      - 'docker-compose.prod.yml' # On dÃ©ploie aussi si on change la config docker

jobs:
  # --- JOB 1 : BUILD & PUSH (Celui qu'on avait dÃ©jÃ ) ---
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qcm-backend:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qcm-frontend:latest

  # --- JOB 2 : DEPLOY (Le nouveau !) ---
  deploy:
    needs: build-and-push # Attends que le build soit fini
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd devops-ci-cd-project
            
            # 1. Mise Ã  jour du code (docker-compose.yml etc)
            git fetch --all
            git reset --hard origin/main
            
            # 2. ARRÃŠT TOTAL (LibÃ¨re les ports et supprime les conteneurs)
            docker compose -f docker-compose.prod.yml down
            
            # 3. SUPPRESSION DE L'IMAGE FRONTEND (Pour forcer le retÃ©lÃ©chargement)
            # (Le "|| true" Ã©vite que Ã§a plante si l'image n'existe pas encore)
            docker rmi herve19944/qcm-frontend:latest || true
            docker rmi herve19944/qcm-backend:latest || true
            
            # 4. TÃ‰LÃ‰CHARGEMENT PROPRE
            docker compose -f docker-compose.prod.yml pull
            
            # 5. DÃ‰MARRAGE
            docker compose -f docker-compose.prod.yml up -d
            
            # 6. MÃ©nage final
            docker image prune -f